FROM postgres:16-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685

COPY postgres-entrypoint.sh /usr/local/bin/digiforge-postgres-entrypoint.sh
COPY postgres/001-createdb.sql /docker-entrypoint-initdb.d/001-createdb.sql

RUN chmod 755 /usr/local/bin/digiforge-postgres-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/digiforge-postgres-entrypoint.sh"]
CMD ["postgres"]
